CREATE TABLE `audit_events` (
  `id` VARCHAR(191) NOT NULL,
  `event_id` VARCHAR(64) NOT NULL,
  `occurred_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `actor_type` VARCHAR(16) NOT NULL DEFAULT 'user',
  `actor_id` VARCHAR(64) NULL,
  `actor_role` VARCHAR(32) NULL,
  `action` VARCHAR(96) NOT NULL,
  `resource_type` VARCHAR(64) NOT NULL,
  `resource_id` VARCHAR(191) NULL,
  `project_id` VARCHAR(64) NULL,
  `source` VARCHAR(24) NOT NULL DEFAULT 'api',
  `outcome` VARCHAR(16) NOT NULL,
  `reason_code` VARCHAR(96) NULL,
  `request_id` VARCHAR(64) NULL,
  `correlation_id` VARCHAR(128) NULL,
  `ip_hash` CHAR(64) NULL,
  `user_agent_hash` CHAR(64) NULL,
  `before_hash` CHAR(64) NULL,
  `after_hash` CHAR(64) NULL,
  `changes` JSON NULL,
  `metadata` JSON NULL,
  `event_hash` CHAR(64) NOT NULL,
  `hash_version` VARCHAR(32) NOT NULL DEFAULT 'sha256-v1',
  `retention_class` VARCHAR(24) NOT NULL,
  `expires_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

  UNIQUE INDEX `audit_events_event_id_key`(`event_id`),
  INDEX `audit_events_actor_id_occurred_at_idx`(`actor_id`, `occurred_at`),
  INDEX `audit_events_action_outcome_occurred_at_idx`(`action`, `outcome`, `occurred_at`),
  INDEX `audit_events_resource_type_resource_id_occurred_at_idx`(`resource_type`, `resource_id`, `occurred_at`),
  INDEX `audit_events_project_id_occurred_at_idx`(`project_id`, `occurred_at`),
  INDEX `audit_events_request_id_idx`(`request_id`),
  INDEX `audit_events_correlation_id_idx`(`correlation_id`),
  INDEX `audit_events_retention_class_expires_at_idx`(`retention_class`, `expires_at`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `consultation_runs`
  ADD COLUMN `model_version` VARCHAR(128) NULL,
  ADD COLUMN `tool_summary` JSON NULL,
  ADD COLUMN `output_hash` CHAR(64) NULL,
  ADD COLUMN `human_audit_event_id` VARCHAR(64) NULL,
  ADD INDEX `consultation_runs_human_audit_event_id_idx`(`human_audit_event_id`);
